### ISSUE TITLE
Relaunch website

### ISSUE THREAD

**Issue by ghost** [x3dom/x3dom.org#6]
The current website is a blog continuously hacked towards maintainability nightmare. The redesign should provide:
- improved information architecture
- a cleaner visual design (good readability, sympathetic colors, easy to find information)
- same look and feel for all parts of the site (blog, documentation, etc.)
- maintainable backend technology (no wordpress, except for the blog)
- complete local development environment (no hacking on the live server)
- getting rid of wordpress would be nice, requires more planning. Jailing it to /blog/ would do fine for now
- having community feed aggregation would be nice
- integrate social media

**Comment by timmjd** [comment]
moved to milestone
